### ISSUE TITLE
fatal: repository 'https://github.com/dmail/node-stacktrace.git/' not found

### ISSUE THREAD

**Issue by eugene-sea** [dmail/system-node-sourcemap#1]
If I try to install the package:

```
npm i system-node-sourcemap --save
```

I get error:

```
fatal: repository 'https://github.com/dmail/node-stacktrace.git/' not found
```

It looks like this package no longer exists on GitHub.

Could you fix it?

**Comment by dmail** [comment]
Install was failing because node-stacktrace became a private repo but I've reverted this and it will remains definitively public.

For your information, I made this repo because https://github.com/evanw/node-source-map-support don't work with SystemJS due to this line https://github.com/systemjs/systemjs/blob/d3196ce9fd877f423757f7ad415fd75110956043/dist/system.src.js#L125. I don't need this anymore because I now use a different approach but I guarantee to let this work accessible on github.

**Comment by eugene-sea** [comment]
Thank you
